#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := UnBanco_Client

COMPONENT_ADD_INCLUDEDIRS := components/include

include $(MDF_PATH)/project.mk
